# Generated by Django 3.1.3 on 2021-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201215_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Sub-categories',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_name',
            field=models.ManyToManyField(blank=True, to='products.SubCategory'),
        ),
    ]
