# Generated by Django 3.1.3 on 2021-01-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210114_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category_name',
            new_name='sub_category',
        ),
    ]
