# Generated by Django 3.1.3 on 2020-12-14 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 19, 42, 27, 656224)),
        ),
    ]
