# Generated by Django 3.1.3 on 2020-12-15 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201215_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(blank=True, default='within 3 days', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 17, 50, 28, 375514)),
        ),
    ]
