# Generated by Django 3.1.3 on 2021-01-07 19:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201215_1407'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_auto_20210107_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 19, 27, 43, 5337)),
        ),
    ]
