# Generated by Django 3.1.3 on 2021-01-07 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210107_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 19, 59, 17, 571718)),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
    ]
