# Generated by Django 4.1.1 on 2022-10-04 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210114_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 1, 28, 31, 939752)),
        ),
    ]
