# Generated by Django 3.1.3 on 2020-12-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20201226_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='payment.countrylist'),
        ),
    ]
